---
- name: Create mail user
  user:
    name: vmail
    home: /var/vmail

- name: Add the rspamd apt key
  apt_key:
    url: https://rspamd.com/apt-stable/gpg.key
    state: present

- name: Add rspamd repository
  apt_repository:
    repo: "deb http://rspamd.com/apt-stable/ stretch main"
    state: present

- name: Update
  apt: update_cache=yes

- name: Upgrade
  apt: upgrade=safe

- name: Install programs
  apt: pkg={{ item }} state=installed
  with_items:
    - certbot
    - mariadb-server
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-mysql
    - dovecot-sieve
    - dovecot-managesieved
    - rspamd
    - redis-server

- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1 {{ fqdn }} {{ hostname }}"
    state: present

- name: Set mailname
  copy:
    dest: "/etc/mailname"
    content: |
      {{ fqdn }}

- name: Restart systemd-logind
  service:
    name: systemd-logind
    state: restarted
